### ISSUE TITLE
Markdown support?

### ISSUE THREAD

**Issue by Zylann** [GeForceLegend/vscode-glsl#2]
I don't know how this works in VSCode, but with Markdown, highlighting of other languages can be injected like this:

![image](https://user-images.githubusercontent.com/1311555/175825485-68ddd023-2015-47ab-a1d1-06d0cef5eeea.png)

I have `vscode-glsl` installed, but even after restarting VSCode, the GLSL snippet is still not highlighted. I write docs with a lot of GLSL in them, it would be useful to have this to reduce mistakes.

**Comment by GeForceLegend** [comment]
This is caused by microsoft doesnt provide glsl block tokens in markdown files, and I have to modify the markdown syntax file in vscode to provide the tokens. Once the tokens are provided, my extension can highlight the words.
![20220627095844](https://user-images.githubusercontent.com/41003546/175846215-2e224ddb-be29-4584-82c9-c1957de747ec.png)

**Comment by GeForceLegend** [comment]
Added in 0.2.4
